version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./user-service:/app
    restart: unless-stopped

  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./product-service:/app
    restart: unless-stopped
